### ISSUE TITLE
Wrap line length, first line not correct

### ISSUE THREAD

**Issue by gbittmann** [babobski/Beautify-js#6] opened 2017-01-27 15:52 UTC
```
                           <p>
                                Every organization we work with is seeking to communicate a message. We help develop
                                that message and make it come to life! Whether on
                                the web or through print and mail, we partner with
                                our customers to take a simple idea and create a
                                tangible reality.
                            </p>
```

The document type is html5 with the wrap near 80 setting as you can see the first line is longer than the rest by quite a bit, well past the 80. The subsequent lines seem to wrap correctly.

**Comment by babobski** [comment] 2017-01-28 10:25
@gbittmann I tried to reproduce but I'm unable to.
When I set my lines to wrap near 80 and run you're code it is wrapping it correct:
```
<p>
	Every organization we work with is seeking to communicate a message. We help develop
	that message and make it come to life! Whether on the web or through print and mail,
	we partner with our customers to take a simple idea and create a tangible reality.
</p>
```

I think I know what the issue is, if you make a selection from tag to tag like this:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/22395879/1bd40362-e54b-11e6-928d-b582d038ba7f.png)

The first line is missing it space before the tag, resulting in a incorrect output.
For the beautifier to work correct it should be a block select:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/22395898/a79a478a-e54b-11e6-9723-d6a6e7e0112c.png)

This can be rather easy to fix from my part, if the selection start is not at the beginning of the line I should extend the selection to the beginning of the line.

So I keep this open as a enhancement request.

**Comment by gbittmann** [comment] 2017-01-30 14:21
I was not using a selection. I was running on the full file with nothing selected when I opened the issue.

I have now also tried selecting the full file, I get the same behavior.

If I select only the paragraph, as indicated in your second example, the lines are evenly wrapped at roughly 80, but I lose the existing indents.

I'm attaching my file in hopes that it can help with duplication.

[home.zip](https://github.com/babobski/Beautify-js/files/739159/home.zip)

**Comment by babobski** [comment] 2017-01-30 17:41
Got it reproduced, I was using a tab character for indent, but this issue appears when you use spaces.
Got it reproduced on the [http://jsbeautifier.org/](http://jsbeautifier.org/) website as well, opened a [issue](https://github.com/beautify-web/js-beautify/issues/1122) for it.

Will apply a fix for it, when it is fixed in the source code.

**Comment by babobski** [comment] 2018-10-13 07:10
They fixed the issue in the main source code, will update the addon pretty soon,

**Closed as completed** 2018-10-14 11:30 UTC
Labels: bug
